version: "3"

services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./data/homebridge:/homebridge

  deconz:
    image: deconzcommunity/deconz:latest
    restart: always
    privileged: true
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./data/deconz:/opt/deCONZ
    devices:
      - ${DECONZ_USB_DEVICE}
    environment:
      - DECONZ_WEB_PORT=8080
      - DECONZ_WS_PORT=8443
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTA=0
